// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSPbackend.Context;

#nullable disable

namespace PSPbackend.Migrations
{
    [DbContext(typeof(PspDbContext))]
    [Migration("20260110020237_AdjustModels")]
    partial class AdjustModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSPbackend.Models.Merchant", b =>
                {
                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BankMerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("FailedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("MerchantPassword")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SucessUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("MerchantId");

                    b.ToTable("Merchants", (string)null);
                });

            modelBuilder.Entity("PSPbackend.Models.MerchantPaymentMethods", b =>
                {
                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MerchantId", "PaymentMethodId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("MerchantPaymentMethods", (string)null);
                });

            modelBuilder.Entity("PSPbackend.Models.PaymentMethod", b =>
                {
                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentMethodType")
                        .HasColumnType("int");

                    b.HasKey("PaymentMethodId");

                    b.HasIndex("PaymentMethodType")
                        .IsUnique();

                    b.ToTable("PaymentMethods", (string)null);
                });

            modelBuilder.Entity("PSPbackend.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("MerchantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Stan")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .IsFixedLength();

                    b.Property<DateTime>("PspTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AcquirerTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<Guid>("GlobalTransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MerchantOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MerchantTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MerchantId", "Stan", "PspTimestamp");

                    b.ToTable("PaymentTransactions", (string)null);
                });

            modelBuilder.Entity("PSPbackend.Models.MerchantPaymentMethods", b =>
                {
                    b.HasOne("PSPbackend.Models.Merchant", "Merchant")
                        .WithMany("MerchantPaymentMethods")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSPbackend.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("PSPbackend.Models.PaymentTransaction", b =>
                {
                    b.HasOne("PSPbackend.Models.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Merchant");
                });

            modelBuilder.Entity("PSPbackend.Models.Merchant", b =>
                {
                    b.Navigation("MerchantPaymentMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
